export const ROUTES = {
  HOME: '/',
  CHARACTER_BUILDER: '/character-builder',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  USERS: '/users',
  CHARACTERS: '/characters',
  CHARACTER: '/characters/:id',
  CAMPAIGNS: '/campaigns',
  CAMPAIGN: '/campaigns/:id',
  RULES: '/campaigns/rules',
  PARTY: '/campaigns/party',
  INVITE: '/invites/:inviteId',
  SESSIONS: '/campaigns/:id/sessions',
  SESSION: '/campaigns/:id/sessions/:sessionId',
  MESSAGING: '/campaigns/:id/messages',
  MESSAGING_CONVERSATION: '/campaigns/:id/messages/:conversationId',
  WORLD: '/campaigns/:id/world',
  WORLD_LOCATIONS: '/campaigns/:id/world/locations',
  WORLD_LOCATION: '/campaigns/:id/world/locations/:locationId',
  WORLD_NPCS: '/campaigns/:id/world/npcs',
  WORLD_NPC: '/campaigns/:id/world/npcs/:npcId',
  WORLD_MONSTERS: '/campaigns/:id/world/monsters',
  WORLD_MONSTER: '/campaigns/:id/world/monsters/:monsterId',
  EQUIPMENT: '/campaigns/:id/equipment',
  EQUIPMENT_DETAILS: '/campaigns/:id/equipment/:equipmentId',
} as const
